/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#a04100',
        'primary-container': '#ff6b00',
        'primary-fixed': '#ffdbcc',
        'on-primary': '#ffffff',
        'on-primary-container': '#572000',
        secondary: '#4f6073',
        'secondary-container': '#d2e4fb',
        'on-secondary': '#ffffff',
        tertiary: '#545f72',
        'tertiary-container': '#8e99ae',
        surface: '#f8f9ff',
        'surface-dim': '#ccdbf4',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d4e4fc',
        'on-surface': '#0d1c2e',
        'on-surface-variant': '#5a4136',
        'on-background': '#0d1c2e',
        background: '#f8f9ff',
        outline: '#8e7164',
        'outline-variant': '#e2bfb0',
        'inverse-surface': '#223144',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#ffb693',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['var(--font-plus-jakarta)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0 8px 40px rgba(13, 28, 46, 0.06)',
        card: '0 2px 20px rgba(13, 28, 46, 0.08)',
        'card-hover': '0 8px 32px rgba(160, 65, 0, 0.15)',
      },
    },
  },
  plugins: [],
}
